---
- hosts: webserver
  become: yes
  tasks:
          - name: i want to install apache2 in ubuntu ansible node 1
            apt:
                    name: "{{apache2onuvuntu}}"
                    state: absent
            when: ansible_os_family == "Debian"  

          - name: I want to install apache2 in redhat ansible node
            yum:
                     name: "{{httpdonredhat}}" 
                     state: present
            when: ansible_os_family == "RedHat" 


