---
# tasks file for mywebrole
          - name: i want to install apache2 in ubuntu ansible node 1111344
            apt:
                    name: apache2
                    state: present
            when: ansible_os_family == "Debian"  

          - name: i want to change apache2 template with jinga template
            template:
                src: template/index.j2
                dest: /var/www/html/index.html