---
# tasks file for mywebrole
          - name: i want to install apache2 in ubuntu ansible node 1111344
            apt:
                    name: appakache2
                    state: present
            when: ansible_os_family == "Debian"  

          - name: I want to install apache2 in redhat ansible node
            yum:
                     name: "httttpd" 
                     state: present
            when: ansible_os_family == "RedHat" 